config/routes.rb
Rails.application.routes.draw do

  root :to => 'users/homes#top'
  get 'about' => 'users/homes#about'

  scope module: :users do
    resources :users, only: [:index, :edit, :update] do
      member do
        get :favorites
        get :confirm
      end
      # フォロー機能のルーティング
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
    end
    # ユーザー詳細画面のルーティング
    get '/users/:id/profile' => 'users#show', as: 'profile'
    # 退会確認画面のルーティング
    get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
    # 論理削除用のルーティング
    patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
    resources :posts do
      resources :post_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    # タグ検索機能のルーティング
    get "search_tag"=>"posts#search_tag"
    # ワード検索のルーティング
    get "search" => "searches#search"
    # グループ機能のルーティング
    resources :groups do
      get "join" => "groups#join"
      delete "all_destroy" => 'groups#all_destroy'
      get "new/mail" => "groups#new_mail"
      get "send/mail" => "groups#send_mail"
    end
  end

  namespace :admin do
    root :to => "homes#top"
    resources :users, only: [:index, :show, :edit, :update]
    resources :tags, only: [:index, :create, :edit, :update]
    resources :posts, only: [:index, :show, :edit, :update]
    get "search_tag"=>"posts#search_tag"
    get "search" => "searches#search"
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip:[:registrations, :passwords],controllers:{
    sessions: "admin/sessions"
  }

  # 顧客用
  # URL /users/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  def index
                                                             # ↓投稿を新しい順にしている
    @posts = Post.where(status: :true).page(params[:page]).per(8).order(id: "DESC")
    @tag_list=Tag.all
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to admin_post_path(@post)
    else
      render "edit"
    end
  end

  def search_tag
    #検索結果画面でもタグ一覧表示
    @tag_list=Tag.all
    @tag=Tag.find(params[:tag_id])
    @posts=@tag.posts.page(params[:page]).per(8)
  end

  private

    def post_params
      params.require(:post).permit(:is_ban)
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    # updateの構文：モデルのインスタンス.update(更新データ)
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "会員情報が更新されました。"
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :introduction, :profile_image, :status, :email, :is_deleted)
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/favorites_controller.rb
class Users::FavoritesController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: @post.id)
    favorite.save
    #render 'replace_btn'
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    #render 'replace_btn'
    redirect_to post_path(@post)
  end

end

app/controllers/users/groups_controller.rb
class Users::GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @user = User.find(params[:id])
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to group_path(@group.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.owned_groups.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def edit
    @group=Group.find(params[:id])
  end

  def update
    @group=Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group.id)
    else
      render "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    #current_userは、@group.usersから消されるという記述。
    @group.users.delete(current_user)
    redirect_to group_path(@group.id)
  end

  def all_destroy
    @group = Group.find(params[:group_id])
    if @group.destroy
    redirect_to groups_path
    end
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content, group_users).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :group_image, :status)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

end

app/controllers/users/homes_controller.rb
class Users::HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/post_comments_controller.rb
class Users::PostCommentsController < ApplicationController

  def create
    post = Post.find(params[:post_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end
  
  def destroy
    PostComment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/users/posts_controller.rb
class Users::PostsController < ApplicationController
  before_action :authenticate_user!


  def index
                                                             # ↓投稿を新しい順にしている
    @posts = Post.where(status: :true).page(params[:page]).per(8).order(id: "DESC")
    @tag_list=Tag.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id
    # 受け取った値を,で区切って配列にする
    tag_list=params[:post][:name].delete(' ').delete('　').split(',')
    if params[:post]
      if @post.save
        @post.save_post(tag_list)
        redirect_to post_path(@post),notice: '投稿完了しました。'
      else
        render:new,notice: '投稿に失敗しました。'
      end
    else
      if @post.update(status: true)
        redirect_to user_path(current_user), notice: "下書き保存しました。"
      else
        render:new, notice: '投稿に失敗しました。'
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_tags = @post.tags
  end

  def edit
    @post = Post.find(params[:id])
    # pluckはmapと同じ意味
    @tag_list = @post.tags.pluck(:name).join(',')
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:name].delete(' ').delete('　').split(',')
    if @post.update(post_params)
      @post.save_post(tag_list)
      redirect_to post_path(@post)
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def search

    @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @posts = Post.looks(params[:search], params[:word])
    end

  end

  def search_tag
    #検索結果画面でもタグ一覧表示
    @tag_list=Tag.all
    @tag=Tag.find(params[:tag_id])
    @posts=@tag.posts.page(params[:page]).per(8)
  end

  private

  def post_params
    params.require(:post).permit(:title, :image, :introduction, :status)
  end

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。'
    end
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    profile_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/relationships_controller.rb
class Users::RelationshipsController < ApplicationController

  # フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー外すとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  # フォロー一覧
  def followings
    @user = User.find(params[:user_id])
    @users = @user.followings
  end

  # フォロワー一覧
  def followers
    @user = User.find(params[:user_id])
    @users = @user.followers
  end

end

app/controllers/users/searches_controller.rb
class Users::SearchesController < ApplicationController

  def search

    @range = params[:range]

    if @range == "会員"
      @users = User.looks(params[:word]).page(params[:page]).per(8).order(id: "DESC")
    else
      @posts = Post.search(params[:word]).page(params[:page]).per(8).order(id: "DESC")
    end

  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # ゲストログイン機能
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to profile_path(user), notice: 'ゲストユーザーでログインしました。'
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  private

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_user
    @user = User.find_by(name: params[:user][:name])
    if @user
      if @user.valid_password?(params[:user][:password]) && (@user.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_user_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:favorites]
  before_action :ensure_guest_user, only: [:edit]

  def index
    @users = User.page(params[:page]).per(8)
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.where(status: :true).page(params[:page]).order(id: "DESC")
  end

  def confirm
    @user = User.find(params[:id])
    @posts = @user.posts.where(status: false).order(id: "DESC").page(params[:page]).per(20)
  end

  def edit
    @user = User.find(params[:id])
    @posts = @user.posts
    if @user.id != current_user.id
    redirect_to profile_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to profile_path(@user.id), notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  def unsubscribe
    @user = current_user
  end

  def withdrawal
    @user = current_user
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path, notice: "退会しました"
  end

  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :profile, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.user_name == "ゲスト"
      redirect_to profile_path(current_user) , notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/posts/_tag.html.erb
<div class="col-2 mt-5">
  <div class="ml-5 pl-5">
    <h4>タグ一覧</h4>
    <ul class="list-group">
      <% @tag_list.each do |list|%>
        <li class="list-group-item">
          <%=link_to list.name,search_tag_path(tag_id: list.id) %>
          <%="(#{list.posts.count})" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/posts/create.html.erb
<h1>Users::Posts#create</h1>
<p>Find me in app/views/users/posts/create.html.erb</p>

app/views/users/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 pt-3">
      <h1>投稿編集画面</h1>

  <%= form_with model: @post do |f| %>
    <h4 class="pt-2">サムネイル画像</h4>
      <%= f.file_field :image, accept: "image/*" %>
    <h4 class="pt-2">タイトル</h4>
      <%= f.text_field :title %>
    <h4 class="pt-2">説明文</h4>
    <div class="rich_area">
      <%= f.rich_text_area :introduction %>
    </div>
    <div class="field pt-2">
      <%= f.label"タグ (,で区切ると複数タグ登録できます)" %><br>
      <%= f.text_field :name, value: @tag_list %>
    </div>

    <!--<div class="form-group">-->
    <!--  <%#=f.label:"公開範囲",class:"col-sm-4"%>-->
    <!--    <div style="padding-right:20px;">-->
    <!--      <%#= f.radio_button :status, :true %>-->
    <!--      <%#= f.label :status, "公開", {value: :true, style: "display: inline-block;"} %>-->
    <!--    </div>-->
    <!--    <div style="padding-right:20px;">-->
    <!--      <%#= f.radio_button :status, :false %>-->
    <!--      <%#= f.label :status, "下書き保存", {value: :false, style: "display: inline-block;"} %>-->
    <!--    </div>-->
    <!--</div>-->

    <%= f.submit '更新', class: 'mt-1' %>
<% end %>
    </div>
  </div>
</div>

app/views/users/posts/index.html.erb
<div class="row">

  <%= render 'tag' %>

<div class='container'>
  <h1 class='mt-3'>投稿一覧</h1>
  <div class="card-deck">
  	<div class="row col-12">
      <% @posts.each do |post| %>
    		<div class="col-sm-3 py-3">
    			<div class="card h-100 shadow-lg">
    				<%= link_to post_path(post.id) do %>
            <%= image_tag post.get_image, size: '180', class:"card-img-top"; %>
            <% end %>
    				<div class="card-body">
    					<h4 class="card-title"><%= link_to post_path(post.id), class:"text-dark" do %><strong><%= post.title %></span></strong><% end %></h4>
    					<%= link_to profile_path(post.user.id), class:"text-dark" do %>
                <%= image_tag post.user.get_profile_image, size: '40x40', class:"rounded-circle" %>
                  <span><%= post.user.user_name %></span><br>
              <% end %>
    				</div>
    			</div>
    		</div>
      <% end %>
  	</div>
  	<div class='mx-auto pt-5'>
      <%= paginate @posts %>
    </div>
  </div>
</div>

</div>

app/views/users/posts/new.html.erb
<div class="container">
  <div class="row">
    <% if current_user.user_name == 'ゲスト' %>
      <div class="col-12 pt-3">
        <h4>ゲストユーザーは投稿ができません</h4>
        <%= render 'users/shared/guest' %>
      </div>
    <% else %>
    <div class="col-12 pt-3">
      <h1>投稿フォーム</h1>
        <%= form_with model: @post do |f| %>
          <h4 class="pt-2">サムネイル画像</h4>
            <%= f.file_field :image, accept: "image/*" %>
          <h4 class="pt-2">タイトル</h4>
            <%= f.text_field :title %>
          <h4 class="pt-2">説明文</h4>
          <div class="rich_area">
            <%= f.rich_text_area :introduction %>
          </div>
          <div class="field">
            <%= f.label"タグ (,で区切ると複数タグ登録できます)" %><br>
            <%= f.text_field :name, value: @tag_list %>
          </div>

          <!--<div class="form-group">-->
          <!--  <%#=f.label:"公開範囲",class:"col-sm-4"%>-->
          <!--    <div style="padding-right:20px;">-->
          <!--      <%#= f.radio_button :status, :true %>-->
          <!--      <%#= f.label :status, "公開", {value: :true, style: "display: inline-block;"} %>-->
          <!--    </div>-->
          <!--    <div style="padding-right:20px;">-->
          <!--      <%#= f.radio_button :status, :false %>-->
          <!--      <%#= f.label :status, "下書き保存", {value: :false, style: "display: inline-block;"} %>-->
          <!--    </div>-->
          <!--</div>-->
          <%= f.submit '投稿', class: 'mt-1' %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/posts/search_tag.html.erb
<div class="row">

  <%= render 'tag' %>

  <div class='container'>
    <h1 class='mt-3'>タグ：<%=@tag.name%>の投稿一覧</h1>
    <div class="card-deck">
    	<div class="row col-12">
        <% @posts.each do |post| %>
      		<div class="col-sm-3 py-3">
      			<div class="card h-100 shadow-lg">
      				<%= link_to post_path(post.id) do %>
              <%= image_tag post.get_image, size: '180', class:"card-img-top"; %>
              <% end %>
      				<div class="card-body">
      					<h4 class="card-title"><%= link_to post_path(post.id), class:"text-dark" do %><strong><%= post.title %></span></strong><% end %></h4>
      					<%= link_to profile_path(post.user.id), class:"text-dark" do %>
                  <%= image_tag post.user.get_profile_image, size: '40x40', class:"rounded-circle" %>
                    <span><%= post.user.user_name %></span><br>
                <% end %>
      				</div>
      			</div>
      		</div>
        <% end %>
    	</div>
    	<div class='mx-auto pt-5'>
        <%= paginate @posts %>
      </div>
    </div>
  </div>

</div>

app/views/users/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 mt-5 mx-auto">
    <% if @post.is_ban? %>
      <h3>この投稿は管理者により非公開になっています</h3>
    <% else %>

    <div class="post-show">
      <%= image_tag @post.get_image, class: 'post-show-image' %>
      <h1 class="mt-5 mb-2"><%= @post.title %></h1>
      <% if current_user.user_name == 'ゲスト' %>
        <P>
          ♡<%= @post.favorites.count %> いいね<br>
          <small>いいねをするにはログインをしてください。</small>
        </P>
      <% else %>
        <% if @post.favorited_by?(current_user) %>
          <p>
            <%= link_to post_favorites_path(@post), method: :delete do %>
              ♥<%= @post.favorites.count %> いいね
            <% end %>
          </p>
          <% else %>
          <p>
            <%= link_to post_favorites_path(@post), method: :post do %>
              ♡<%= @post.favorites.count %> いいね
            <% end %>
          </p>
        <% end %>
      <% end %>
      <div class="row">
        <div class="col-1">
          <%= link_to profile_path(@post.user.id), class:"text-dark" do %>
            <%= image_tag @post.user.get_profile_image, size: '50x50', class: 'mb-5 rounded-circle' %>
          <% end %>
        </div>
        <div class="col-8">
          <%= link_to profile_path(@post.user.id), class:"text-dark" do %>
            <%= @post.user.user_name %>
          <% end %><br>
          <small><%= l @post.created_at %></small>
        </div>
      </div>

      <p>
        <%= @post.introduction %>
      </p>

      <p class="mt-5">タグ：
        <% @post_tags.each do |tag| %>
          <%= link_to tag.name,search_tag_path(tag_id: tag.id)%><%="(#{tag.posts.count})" %>
        <% end %>
      </p>
    </div>

    <div class="mt-2 mb-4">
      <% if @post.user == current_user %>
        <%= link_to "編集", edit_post_path(@post), class: 'btn btn-success' %>
        <%= link_to "削除", post_path(@post), method: :delete, class: 'btn btn-danger' %>
      <% end %>
    </div>

      <div class="comment_area">
        <h4>コメント一覧</h4>
        <p>件数：<%= @post.post_comments.count %></p>
        <table>
          <tbody class='table'>
            <% @post.post_comments.each do |post_comment| %>
              <tr>
                <td><%= image_tag post_comment.user.get_profile_image, size: '50x50', class: 'rounded-circle' %></td>
                <td><%= post_comment.user.user_name %></td>
                <td><small><%= l post_comment.created_at %></small></td>
                <td><%= post_comment.comment %></td>
                <td class='col-2'>
                  <% if post_comment.user == current_user %>
                  <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
      <% if current_user.user_name == 'ゲスト' %>
        <div class="mt-5">
          <p>
            ゲストユーザーはコメントできません。<br>
            コメントをするにはログイン、または会員登録をしてください。
          </p>
        </div>
      <% else %>
        <div class="mt-5">
          <%= form_with model: [@post, @post_comment] do |f| %>
            <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: 'col-md-8' %>
            <%= f.submit "コメントする" %>
          <% end %>
        </div>
      <% end %>


    <% end %>
    </div>
  </div>
</div>